### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome" : "Produto Teste",
    "descricao" : "Descrição do Produto Teste",
    "foto" : "path/para/imagem.jpg",
    "valor_unitario" : 100.00
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Novo Produto",
    "descricao" : "Nova Descrição do Produto",
    "foto" : "path/para/nova-imagem.jpg",
    "valor_unitario" : 150.00
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1
