### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1
### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1
### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json
{
"nome_produto" : "Abc da Silva",
"matricula" : "01923874656",
"fabricacao" : "49988234567",
"validade" : "bolinhas",
"matricula" : "12345",
"grupo" : 1
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json
{
"nome_produto" : "Bolinha dos testes",
"matricula" : "019238746567",
"fabricacao" : "499882345679",
"validade" : "1234567",
"matricula" : "123456",
"grupo" : 2
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1